### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/scala/JavaTypeable$

### ISSUE THREAD

**Issue by camper42** [housepower/spark-clickhouse-connector#152]
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/scala/JavaTypeable$
  at xenon.clickhouse.format.JSONEachRowSimpleOutput$.deserialize(JSONOutputFormat.scala:32)
  at xenon.clickhouse.grpc.GrpcNodeClient.$anonfun$syncQueryAndCheckOutputJSONEachRow$1(GrpcNodeClient.scala:97)
  at xenon.clickhouse.grpc.GrpcNodeClient.executeQuery(GrpcNodeClient.scala:187)
  at xenon.clickhouse.grpc.GrpcNodeClient.syncQuery(GrpcNodeClient.scala:167)
  at xenon.clickhouse.grpc.GrpcNodeClient.syncQueryAndCheck(GrpcNodeClient.scala:175)
  at xenon.clickhouse.grpc.GrpcNodeClient.syncQueryAndCheckOutputJSONEachRow(GrpcNodeClient.scala:97)
  at xenon.clickhouse.ClickHouseCatalog.initialize(ClickHouseCatalog.scala:68)
```

[jackson-module-scala](https://github.com/FasterXML/jackson-module-scala) add JavaTypeable since 2.13.0

spark-3.2 release with 2.12.3

---

any suggestions for spark-3.2 ?

If it's easy to fix, I'm happy to help, otherwise I choose to upgrade to spark-3.3

**Comment by pan3793** [comment]
How to reproduce? The CI should cover this I think

**Comment by camper42** [comment]
maven central only has 0.2.1, build 0.4.0-SNAPSHOT and private release myself

build an spark image with jar added to `$SPARK_HOME/jars`，and `df.filter('user_id % 2 != 0').repartition('event_name').writeTo("`ck-datasupport-1`.log_local").append()`

**Comment by camper42** [comment]
`spark.clickhouse.write.repartitionByPartition=false`

**Comment by camper42** [comment]
I will check whether today's snapshot can reproduce

**Comment by camper42** [comment]
latest snapshot has same error

```
FROM internal.xxx/org/spark:3.2.1

RUN ... && \
    cd /usr/local/spark/jars && \
    curl -sLO https://oss.sonatype.org/service/local/repositories/snapshots/content/com/github/housepower/clickhouse-spark-runtime-3.2_2.12/0.4.0-SNAPSHOT/clickhouse-spark-runtime-3.2_2.12-0.4.0-20220711.021737-23.jar
```

above is what Dockfile looks like

below is how we use connector
```
    df.filter('user_id % 2 == 0').repartition('app_event_name').writeTo("`ck-2`.applog.log_daily_local").append()
```

**Comment by camper42** [comment]
set `jackson_version=2.12.3` in `gradle.properties` and do a private release, everything looks good now

**Comment by camper42** [comment]
yep，why use shaded jar ?
what are the advantages over specifying version in `spark-3.2/spark-3.3` directory? (just curious

**Comment by pan3793** [comment]
I'd like to say using different versions for Spark 3.2 and 3.3 is a simple solution, the only breaking case is if we run the build command w/ `-Dspark_binary_versions=3.2,3.3`, the module `clickhouse-core` is actually compiled one time

**Comment by pan3793** [comment]
I just merge the #153, would you please take a try?

**Comment by camper42** [comment]
#153 works fine, writting to the clickhouse local table is about 8 times faster 😃

and may have found a bug about `spark.clickhouse.write.repartitionNum`, I will send another issue for it

**Comment by pan3793** [comment]
Thanks for confirmation!

**Comment by pan3793** [comment]
> ...specifying version in `spark-3.2/spark-3.3` directory

After second thought, I adopt this way in https://github.com/housepower/spark-clickhouse-connector/commit/5dbc2fdd923d9685045682b057f5864fd3f19ec5
