### ISSUE TITLE
The nullable attribute in the shema not be handled when creating the table with pyspark

### ISSUE THREAD

**Issue by sketchmind** [housepower/spark-clickhouse-connector#167]
pyspark version:3.2.0
spark-clickhouse-connector:0.4.0

code：
![image](https://user-images.githubusercontent.com/39169452/180917910-98dd8570-387a-4e2c-9c88-f1d86c40a319.png)

output:
![image](https://user-images.githubusercontent.com/39169452/180917820-c057ac1e-c864-4054-922c-b2a7d5ce9dab.png)
![image](https://user-images.githubusercontent.com/39169452/180918128-5e22fc6d-9646-470f-a19f-90f28368d8dc.png)

**Comment by pan3793** [comment]
It's by design https://github.com/apache/spark/pull/25536

**Comment by sketchmind** [comment]
> It's by design [apache/spark#25536](https://github.com/apache/spark/pull/25536)

But if this specification is followed, a not null clickhouse table cannot be automatically created using the spark API, and if the table is created in advance, it cannot be replaced because the metadata in zookeeper is different

**Comment by pan3793** [comment]
I am also confusing w/ this behavior, but unfortunately, Spark does not support reserving the nullability of data when using CTAS.

**Comment by pan3793** [comment]
Opened https://github.com/apache/spark/pull/41070 to try solving this problem on upstream
