### ISSUE TITLE
Does this project support Spark 3.1?

### ISSUE THREAD

**Issue by melin** [housepower/spark-clickhouse-connector#19]

**Comment by pan3793** [comment]
No.
Data Source V2 API is evolving, this project uses the interface/catalyst rules added in Spark 3.2.0, such as `RequiresDistributionAndOrdering` which is introduced in [SPARK-34026](https://issues.apache.org/jira/browse/SPARK-34026).

You can change the `spark.version` to 3.1.2 in file `gradle.properties` and build this project, removing those not supported interface and code.
