### ISSUE TITLE
Using connector with structured streaming

### ISSUE THREAD

**Issue by step4** [housepower/spark-clickhouse-connector#200]
I am using pyspark and this connector to write into a clickhouse cluster.
With normal batch dataframes everything seems to work.

Now I want to rewrite my job to use structured streaming to writes results from a delta table to the clickhouse cluster.

Is there a way to use the `writeStream` functionality or do I have to use the `foreachBatch` function?

**Comment by pan3793** [comment]
Thanks for sharing your use case, currently, this connector does not support streaming writing, please use `foreachBatch` way.

**Comment by step4** [comment]
Thanks for clarification.
