### ISSUE TITLE
Using SSL with Spark SQL

### ISSUE THREAD

**Issue by cevenrokt** [housepower/spark-clickhouse-connector#201]
Hi,

I am trying to connect to clickhouse using SSL with pyspark SQL.
I successfully did it with JDBC, but I couldn't find the option for spark SQL. For Spark SQL, I only managed to connect to a cluster that did not require SSL. When trying to connect to a cluster that requires SSL, I got `Read timed out`: see [stacktrace.txt](https://github.com/housepower/spark-clickhouse-connector/files/9915733/stacktrace.txt) 

I tried with both `http` and `https` for `spark.sql.catalog.clickhouse.protocol`, without success. I could not find an option for SSL in https://github.com/housepower/spark-clickhouse-connector/blob/ad3ddf4d01e365ab0b6cc9ffbd3785c10bade590/spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/Constants.scala 

My Spark configuration for clickhouse is:

```
{
  'spark.sql.catalog.clickhouse.protocol': 'http', 
  'spark.sql.catalog.clickhouse': 'xenon.clickhouse.ClickHouseCatalog', 
  'spark.sql.catalog.clickhouse.http_port': '8123', 
  'spark.sql.catalog.clickhouse.database': 'default',
  'spark.sql.catalog.clickhouse.host': 'clickhouse', 
  'spark.sql.catalog.spark_catalog': 'xenon.clickhouse.ClickHouseCatalog
}
```

FYI, the JDBC config below was successful with SSL:
```
dataframe.write \
    .format('jdbc') \
    .option('driver', 'com.clickhouse.jdbc.ClickHouseDriver') \
    .option('ssl', 'true') \
    .option('url', 'clickhouse') \
    .option('dbtable', 'clickhouse_table') \
    .mode('append') \
    .save()
```

Spark version: 3.2
Jars: `clickhouse-spark-runtime-3.2_2.12-0.5.0.jar` and `clickhouse-jdbc-0.3.2-patch11-all.jar`
Language: python

Could you unblock me for SSL config with Spark SQL?

**Comment by mtgnoah** [comment]
Did that jbdc config work for a cluster without ssl?

**Comment by cevenrokt** [comment]
@mtgnoah it worked for a cluster *with* SSL

**Comment by genzgd** [comment]
I think you need a combination of `https` protocol and the correct `http_port`, which is probably 8443 and not 8123.  I believe the `ssl` setting is only relevant if you are using the `native` protocol on the native TLS port 9440.

**Comment by cevenrokt** [comment]
@genzgd I fixed my cluster port to be `8443` for https but still can't get spark SQL to work, I think it's a library shortcoming which I detailed below. Can you help with investigating further?

According to https://github.com/housepower/spark-clickhouse-connector/blob/9d19fcca843c67fc10982bedcac56c14f55234f4/spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala#L52 , I have to use a protocol defined in enum values: https://github.com/ClickHouse/clickhouse-jdbc/blob/42b1b2193931dc68b86cb5dfc86392d4c6d6601b/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseProtocol.java#L10-L59 

So only options in my case are 'http' or 'tcp'
However, the Spark connector only seem to support 'http' or 'grpc', not 'tcp': see https://github.com/housepower/spark-clickhouse-connector/blob/d7720a80450958576a3bb0f7fd3d095c8f2e7175/spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/Constants.scala#L17-L39 

In addition, the `Constants.scala` above does not provide an ssl config option.

With my configuration, the connector wrongly uses `http` instead of `https` when building the url, and times out on queries:

```
spark.sql('use clickhouse;')
...
159] Read timed out, server ClickHouseNode [uri=http://clickhouse:8443/default]@-794515097
```
```
{
  'spark.sql.catalog.clickhouse.protocol': 'http', 
  'spark.sql.catalog.clickhouse': 'xenon.clickhouse.ClickHouseCatalog', 
  'spark.sql.catalog.clickhouse.http_port': '8443', 
  'spark.sql.catalog.clickhouse.database': 'default',
  'spark.sql.catalog.clickhouse.host': 'clickhouse', 
  'spark.sql.catalog.spark_catalog': 'xenon.clickhouse.ClickHouseCatalog
}
```

**Comment by pan3793** [comment]
Thanks for reporting and investigating, yes, it does not support setting arbitrary options for the `ClickHouseClient`, I'm thinking to allow user setting them by

```
spark.sql.catalog.<catalog_name>.option.<option1>=value1
spark.sql.catalog.<catalog_name>.option.<option2>=value2
...
```

And converting them to the `Map<ClickHouseOption, Serializable>` by calling `ClickHouseConfig#toClientOptions`, then passing to `ClickHouseClient`

**Comment by pan3793** [comment]
> Read timed out, server ClickHouseNode [uri=http://clickhouse:8443/default]@-794515097

it does not matter, just for displaying

**Comment by cevenrokt** [comment]
@pan3793 that would be great! I am very interested in that use case for an application. Is there any chance to expedite the work, or at least add support for TCP connections and SSL?

**Comment by pan3793** [comment]
Currently, this connector depends on https://github.com/ClickHouse/clickhouse-jdbc, which does not support TCP protocol yet.

**Comment by mtgnoah** [comment]
Did you end up finding a workaround to enable the use of SSL?

**Comment by pan3793** [comment]
Implemented in https://github.com/housepower/spark-clickhouse-connector/pull/203
