### ISSUE TITLE
Custom options don't work

### ISSUE THREAD

**Issue by anotherbugmaster** [housepower/spark-clickhouse-connector#230]
Related: #203

I'm trying to use `ssl` and `sslmode` options, but it seems like jdbc client gets `option.ssl` and `option.sslmode` instead. I'm not too good with Scala, but from what I gather we don't remove prefixes after applying a filter here:

https://github.com/housepower/spark-clickhouse-connector/blob/master/spark-3.3/clickhouse-spark/src/main/scala/xenon/clickhouse/ClickHouseHelper.scala#L47-L69

**Comment by pan3793** [comment]
Thanks for reporting and digging, you are right, let me fix it

**Comment by pan3793** [comment]
v0.6.1 is released, and the jar will be available in Maven Central soon. (maybe a few hours)
https://github.com/housepower/spark-clickhouse-connector/releases/tag/v0.6.1
