### ISSUE TITLE
FixedString should be BinaryType

### ISSUE THREAD

**Issue by clouds56** [housepower/spark-clickhouse-connector#250]
https://github.com/housepower/spark-clickhouse-connector/blob/d1f30ef8cf20b1fa6e18af87ecdf16a3993d3692/spark-3.3/clickhouse-spark/src/main/scala/org/apache/spark/sql/clickhouse/SchemaUtils.scala#L28

According to type mapping https://github.com/ClickHouse/clickhouse-java/blob/c25ffc62c886c0cdc1fcf8d8bf2234690c131dca/clickhouse-data/README.md#type-mapping

**Comment by pan3793** [comment]
Sounds reasonable
