### ISSUE TITLE
Table system.cluster not exist

### ISSUE THREAD

**Issue by fengjian428** [housepower/spark-clickhouse-connector#252]
I'm using spark 3.3.2 
   --packages com.github.housepower:clickhouse-spark-runtime-3.3_2.12:0.7.1,com.clickhouse:clickhouse-jdbc:0.4.5-all
when execute use clickhouse, I got error below
xenon.clickhouse.exception.CHServerException: [HTTP]default@127.0.0.1:8123}/default [60] Code: 60. DB::Exception: Table system.clusters doesn't exist. (UNKNOWN_TABLE) (version 22.6.1.1)

**Comment by pan3793** [comment]
system.clusters is a system table, should be existed on every clickhouse instance, does it real not exist?

**Comment by fengjian428** [comment]
> system.clusters is a system table, should exist on every clickhouse instance, does it really not exist?

sorry, this is because we remove it in the internal ck version.
