### ISSUE TITLE
有计划发布版本，提交到maven 中央仓库？

### ISSUE THREAD

**Issue by melin** [housepower/spark-clickhouse-connector#26]
有计划发布版本，提交到maven 中央仓库？方便直接使用

**Comment by pan3793** [comment]
Not yet, you can follow the [document](https://housepower.github.io/spark-clickhouse-connector/quick_start/01_preparation/#publish-to-private-repository) to publish it to your private repo.

**Comment by pan3793** [comment]
It's available on maven central now.
