### ISSUE TITLE
Plan to support Spark 3.5?

### ISSUE THREAD

**Issue by camper42** [housepower/spark-clickhouse-connector#279]
We're excited about some of the improvements in Spark 3.5, e.g.:

- Allow ShuffleDriverComponent to declare if shuffle data is reliably stored [SPARK-42689](https://issues.apache.org/jira/browse/SPARK-42689)
- Allow V2 writes to indicate advisory shuffle partition size [SPARK-42779](https://issues.apache.org/jira/browse/SPARK-42779)

Any plan on support Spark 3.5?

**Comment by pan3793** [comment]
would like to find a time to complete it soon.
