### ISSUE TITLE
Transfer project to @housepower organization

### ISSUE THREAD

**Issue by pan3793** [housepower/spark-clickhouse-connector#4]
Hi @housepower members,

I'd like to propose transfer this project from my own repository to @housepower's repository.

The project is an Apache Spark DataSource V2 API implementation for ClickHouse, it could be considered as a data source plugin of Apache Spark.

The vision of this project is to provide a seamless user experience for Spark users to access ClickHouse.

The project is currently in a very early stage. Basically, it uses gRPC protocol and `JSON`-relative serialization to communicate to the ClickHouse server, support write/read both single ClickHouse node and ClickHouse cluster, see more detail in the integration tests which under module `clickhouse-spark-31-integration`.

Spark DataSourceV2 API is on rapid development, due to the limitation of development resources, the project currently only supports Spark 3.1.x.

Looking forward to your feedback and thank you very much.

**Comment by pan3793** [comment]
cc @lamberken @shijiyu @sundyli @zhang2014

**Comment by sundy-li** [comment]
Great, this project has brought a very good bridge connection between ClickHouse and Spark.

**Comment by pan3793** [comment]
Transfer done.
