### ISSUE TITLE
Support Map Type?

### ISSUE THREAD

**Issue by camper42** [housepower/spark-clickhouse-connector#58]

**Comment by pan3793** [comment]
Not yet.

Have a quick look of the description of Map type.

For ClickHouse

> Map(key, value) data type stores key:value pairs.
> 
> Parameters
> key — The key part of the pair. String, Integer, LowCardinality, or FixedString.
> value — The value part of the pair. String, Integer, Array, LowCardinality, or FixedString.

For Spark

> MapType(keyType, valueType, valueContainsNull): Represents values comprising a set of key-value pairs. The data type of keys is described by keyType and the data type of values is described by valueType. For a MapType value, keys are not allowed to have null values. valueContainsNull is used to indicate if values of a MapType value can have null values.

As we don't support `LowCardinality` yet, other than that, the rest seem to be a good match overall.

You can expect this feature to be available in a week or two. 

BTW, do you need the key support types other than `String`?

**Comment by camper42** [comment]
thx for reply，currently only string type key in our usage

**Comment by pan3793** [comment]
Thanks for verification, because currently we use JSON for data serialization, key type other than String may cause unexpected behavior, will investigate it later.

**Comment by pan3793** [comment]
@camper42 FYI, implemented.

**Comment by camper42** [comment]
thx
