### ISSUE TITLE
 How to create tables on a cluster at the same time

### ISSUE THREAD

**Issue by sketchmind** [housepower/spark-clickhouse-connector#59]
How to  use datawriterV2 method createOrPeplace to create table like 'CREATE TABLE IF NOT EXISTS test.spark ON CLUSTER testcluster' in SQL

**Comment by sketchmind** [comment]
According the source code,  add a cluster table property can solve this problem

**Comment by pan3793** [comment]
Sorry, I miss this question. You are right, you can pass the `cluster` through `TBLPROPERTIES`. Besides, you can also use `ClickHouseCommandRunner` to run native clickhouse sql.

**Comment by sketchmind** [comment]
> Sorry, I miss this question. You are right, you can pass the `cluster` through `TBLPROPERTIES`. Besides, you can use `ClickHouseCommandRunner` to run native clickhouse sql.

thanks
