### ISSUE TITLE
Replacing table that created by on cluster statement will failed 

### ISSUE THREAD

**Issue by sketchmind** [housepower/spark-clickhouse-connector#61]
Using createOrReplace method in Spark DataSourceV2, when the table created on cluster, replace will failed with 'Table xxx(other node of cluster) already exists'.

**Comment by pan3793** [comment]
Which you clickhouse-server version? Are you using Atomic Database Engine?

**Comment by pan3793** [comment]
https://kb.altinity.com/engines/altinity-kb-atomic-database-engine/

**Comment by sketchmind** [comment]
> Which your clickhouse-server version? Are you using Atomic Database Engine?

Version is 21.3.7.62 (official build)  and it's the engine

**Comment by pan3793** [comment]
It's because the async `DROP TABLE` does not take effect immediately, then breaks `createOrReplace`. I think it's good to add a configuration `spark.clickhouse.drop.table.sync` and set it to `true` in default, because `atomic` is default database engine in recent ClickHouse releases.

**Comment by sketchmind** [comment]
I set this property but it didn't solve the problem，I'm guessing the problem is caused by not using the on cluster statement when deleting the table during the replacement process
![image](https://user-images.githubusercontent.com/39169452/160140263-09185299-73d5-4123-bbad-9f2ec6981225.png)

**Comment by pan3793** [comment]
You are right, the project does not handle all cases for clusterClause properly.
